name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.7
        action:
          - TEST=basic

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache
          ~/.local
        key: cache-${{ runner.os }}-py${{ matrix.python-version }}
        restore-keys: |
          cache-${{ runner.os }}-py${{ matrix.python-version }}

    - name: Setup dependencies
      run: |
        echo "PATH=$PATH:~/.local/bin" >> $GITHUB_ENV
        echo "Python ${{matrix.python-version}}"
        echo "pip: $(type pip)"

        pip install --user --upgrade pip setuptools wheel
        pip install --user pytest
        pip install --user better_exchook

    - name: Run test
      run: |
        export ${{ matrix.action }}
        if [[ ! -z "$TEST" ]]; then
          pytest tests/test_$TEST.py
        fi
        if [[ ! -z "$RUN" ]]; then $RUN; fi
